targets:
  $default:
    builders:
      freezed:
        enabled: true
        options:
          build_extensions:
            'lib/presentation/{{path}}/{{file}}.dart': 'lib/gen/{{path}}/{{file}}.freezed.dart'
            'lib/domain/{{path}}/entities/{{file}}.dart': 'lib/gen/{{path}}/{{file}}.freezed.dart'
      source_gen|combining_builder:
        enabled: true
        options:
          build_extensions:
            'lib/presentation/{{path}}/{{file}}.dart': 'lib/gen/{{path}}/{{file}}.g.dart'
            'lib/domain/{{path}}/entities/{{file}}.dart': 'lib/gen/{{path}}/{{file}}.g.dart'
